//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        public int Coupon_id { get; set; }
        public string Coupon_Code { get; set; }
        public decimal Discount { get; set; }
        public bool IsActive { get; set; }
        public int Admin_id { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
